//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        internal static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capítulo.
        /// </summary>
        internal static string Capitulo {
            get {
                return ResourceManager.GetString("Capitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición moderna.
        /// </summary>
        internal static string EdicionModerna {
            get {
                return ResourceManager.GetString("EdicionModerna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extracto.
        /// </summary>
        internal static string Extracto {
            get {
                return ResourceManager.GetString("Extracto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a extractos.
        /// </summary>
        internal static string Extractos {
            get {
                return ResourceManager.GetString("Extractos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro de búsqueda.
        /// </summary>
        internal static string FiltroBusqueda {
            get {
                return ResourceManager.GetString("FiltroBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Florilegio.
        /// </summary>
        internal static string Florilegio {
            get {
                return ResourceManager.GetString("Florilegio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro.
        /// </summary>
        internal static string Libro {
            get {
                return ResourceManager.GetString("Libro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando.
        /// </summary>
        internal static string Mostrando {
            get {
                return ResourceManager.GetString("Mostrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obra.
        /// </summary>
        internal static string Obra {
            get {
                return ResourceManager.GetString("Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error.
        /// </summary>
        internal static string OperacionCancelada {
            get {
                return ResourceManager.GetString("OperacionCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación completada.
        /// </summary>
        internal static string OperacionCompletada {
            get {
                return ResourceManager.GetString("OperacionCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador.
        /// </summary>
        internal static string Operador {
            get {
                return ResourceManager.GetString("Operador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página.
        /// </summary>
        internal static string Pagina {
            get {
                return ResourceManager.GetString("Pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poema.
        /// </summary>
        internal static string Poema {
            get {
                return ResourceManager.GetString("Poema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuento.
        /// </summary>
        internal static string Recuento {
            get {
                return ResourceManager.GetString("Recuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  resultados.
        /// </summary>
        internal static string Resultados {
            get {
                return ResourceManager.GetString("Resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos.
        /// </summary>
        internal static string SeleccionarTodos {
            get {
                return ResourceManager.GetString("SeleccionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subcapítulo.
        /// </summary>
        internal static string Subcapitulo {
            get {
                return ResourceManager.GetString("Subcapitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TLL.
        /// </summary>
        internal static string TLL {
            get {
                return ResourceManager.GetString("TLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver arriba.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última actualización:.
        /// </summary>
        internal static string UltimaActualizacion {
            get {
                return ResourceManager.GetString("UltimaActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado resultados.
        /// </summary>
        internal static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vernácula.
        /// </summary>
        internal static string Vernacula {
            get {
                return ResourceManager.GetString("Vernacula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verso final.
        /// </summary>
        internal static string VersoFinal {
            get {
                return ResourceManager.GetString("VersoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verso inicial.
        /// </summary>
        internal static string VersoInicial {
            get {
                return ResourceManager.GetString("VersoInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
